<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_Login_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d0c37803-6427-46ba-966f-15f06a54c5b5</testSuiteGuid>
   <testCaseLink>
      <guid>fa3c59fc-fce5-492e-b2f7-b4af0f5484b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Amazon/TC_login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>38aaa7a4-aaaa-41e9-88d4-9135a7328f04</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_Login_Excel/Amazon_Excel_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>38aaa7a4-aaaa-41e9-88d4-9135a7328f04</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>0b6d79b5-fcb6-4ec1-8b34-f4110fff2fd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>38aaa7a4-aaaa-41e9-88d4-9135a7328f04</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>23deeed2-5aba-44a9-afbc-e32a1a031ad2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
